In [ ]:
import numpy as np #day-1: 23/02/2024
# Creating arrays
arr = np.array([1, 2, 3, 4, 5], dtype=int)
print(arr)



[1 2 3 4 5]


In [ ]:
zeros_arr = np.zeros((3, 3), dtype=float)
print(zeros_arr)
ones_arr = np.ones((2, 2), dtype=int)
print(ones_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1 1]
 [1 1]]


In [ ]:
a= np.arange(0,100,5)
print(a)
a=np.savetxt("/content/data.txt", a)


[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [ ]:
#array manipulation
arr = np.array([1, 2, 3, 4, 5])
reshaped_arr = arr.reshape(5, 1)
print(reshaped_arr)
sliced_arr = arr[2:4]
print(sliced_arr)
a=np.array([1,2,3,4,5,6,7,8])
b =a.T
print(b)
b=np.split(a,4)
print(b)

[[1]
 [2]
 [3]
 [4]
 [5]]
[3 4]
[1 2 3 4 5 6 7 8]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c=np.dot(a,b)
print(c)
d = np.linalg.eig(c)
print(d)


[[19 22]
 [43 50]]
EigResult(eigenvalues=array([5.80198014e-02, 6.89419802e+01]), eigenvectors=array([[-0.75781077, -0.40313049],
       [ 0.65247439, -0.91514251]]))


In [ ]:
import numpy as np
data = np.loadtxt("/content/drive/MyDrive/Dataset/dap1.txt",dtype=int)
d = np.savetxt("/content/dap1.txt",data)
print(d)
print(data)

None
[[1 2 3 4 5]
 [3 4 5 6 7]]


<ipython-input-10-7869d7a06dfe>:2: DeprecationWarning: loadtxt(): Parsing an integer via a float is deprecated.  To avoid this warning, you can:
    * make sure the original data is stored as integers.
    * use the `converters=` keyword argument.  If you only use
      NumPy 1.23 or later, `converters=float` will normally work.
    * Use `np.loadtxt(...).astype(np.int64)` parsing the file as
      floating point and then convert it.  (On all NumPy versions.)
  (Deprecated NumPy 1.23)
  data = np.loadtxt("/content/drive/MyDrive/Dataset/dap1.txt",dtype=int)


In [ ]:

a=np.random.rand()
print(a)
b=np.random.randint(0,200)
print(b)

0.4555754961997577
67


In [ ]:
a=np.linspace(0.8,2,5)
print(a)

[0.8 1.1 1.4 1.7 2. ]


In [ ]:
from numpy import random
a=np.ones(((2,3)),dtype=int)
print(a)
print(a.sum())
print(a.sum(axis=0))
print(a.min())
print(a.max())

[[1 1 1]
 [1 1 1]]
6
[2 2 2]
1
1


In [ ]:
a=np.floor(np.random.random((2,2)))
print(a)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
a=np.array([[1,2],[3,4]])
print(a.cumsum(axis=0))
print(a.cumsum(axis=1))


[[1 2]
 [4 6]]


In [ ]:
a=np.array([[1,2],[3,4]])
print(a.max(axis=0))
print(a.max(axis=1))
print(a.min(axis=0))
print(a.min(axis=1))

[3 4]
[2 4]
[1 2]
[1 3]


In [ ]:
a=np.array([1,2,3,4,5,6])
print(a.resize(3,2))
print(a)
print(a.shape)

None
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [ ]:
a=np.array([1,2,3,4,5,6])
print(a.resize(3,2))
b=np.array([6,5,4,3,2,1])
print(b.resize(3,2))
print(np.vstack((a,b)))
print(np.hstack((a,b)))


None
None
[[1 2]
 [3 4]
 [5 6]
 [6 5]
 [4 3]
 [2 1]]
[[1 2 6 5]
 [3 4 4 3]
 [5 6 2 1]]


In [ ]:
a=np.arange(30).reshape(2,3,5)
print(a)
print(np.dstack(a))#no.of rows become no.of group
#column becomes rows
#group become column


[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
al= np.eye(4)# day-2: 24/02/2024
print(al)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
a=np.full((3,3),30)
print(a)
print(a.itemsize)

[[30 30 30]
 [30 30 30]
 [30 30 30]]
8


In [ ]:
x=[1,2,3]
a=np.asarray(x)#symmetric matrix
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
x=np.array([1,4,0],float)
y=np.array([2,2,1],float)#sum of multiplication
print(np.inner(x,y))#[1*2=2+4*2=8+0=10]
print(np.outer(x,y))#1*2,1*2,1*1
print(np.cross(x,y))

10.0
[[2. 2. 1.]
 [8. 8. 4.]
 [0. 0. 0.]]
[ 4. -1. -6.]


In [ ]:
a=np.array([1.1,2.1,3.2,4.1,5.1,6.1,7.1])
print(np.rint(a))

[1. 2. 3. 4. 5. 6. 7.]


In [ ]:

a=np.array([1,2,3,4,5])
b=np.array([5,4,3,2,1])
print(np.true_divide(a,b))

[0.2 0.5 1.  2.  5. ]


In [ ]:
a=np.array([1,2,4,4,5,6])
print(np.unique(a))

[1 2 4 5 6]


In [ ]:
a=np.array([[1,2,3,4],[1,2,3,4]])
b=np.array([[1,2,3,4],[1,2,3,4]])
print(np.union1d(a,b))

[1 2 3 4 9]


In [ ]:
a=np.array([[1,2,3,4],[1,6,3,4]])
b=np.array([[1,2,45,4],[1,2,3,4]])
print(np.intersect1d(a,b))
print(np.setdiff1d(a,b))

[1 2 3 4]
[6]


In [ ]:
a=8
b=6
c=np.hypot(a,b)
print(c)

10.0


In [ ]:
x=np.sin(0)
print(x)

0.0


In [ ]:
x=np.array([10,21,30,40,50,60])
y=np.array([20,21,2,20,25,25])
print(np.divmod(x,y))


(array([ 0,  1, 15,  2,  2,  2]), array([10,  0,  0,  0,  0, 10]))


In [ ]:
x=np.array([10,21,30,40,50,60])
y=np.array([20,21,2,20,25,25])
print(np.mod(x,y))


[10  0  0  0  0 10]


In [ ]:
x=np.array([10,21,30,40,50,60])
y=np.array([20,21,2,20,25,25])
print(np.divide(x,y))


[ 0.5  1.  15.   2.   2.   2.4]


In [ ]:
x=np.array([10,21,30,40,50,60])
y=np.array([20,21,2,20,25,25])
print(np.multiply(x,y))
print(np.matmul(x,y))

[ 200  441   60  800 1250 1500]
4251


In [ ]:
from numpy import random
x=random.normal(size=(2,3))
print(x)

[[-1.38773164 -0.18942786  0.97495656]
 [-1.45632372  0.44142698 -0.38410906]]


In [ ]:

x=random.normal(loc=1,scale=2,size=(2,3)) # scale=standard deviation,loc=mean
print(x)

[[ 0.05627323 -2.44658093 -2.81373334]
 [ 0.55723959  0.98190824  1.37312511]]


In [ ]:
x=random.binomial(n=12,p=0.5,size=10) # n=no.of trails,p=probability
print(x)

[ 7 10  5  4  7  5  7  6  5  8]


In [ ]:
x=random.poisson(lam=2,size=10)
print(x)

[2 1 2 1 3 3 4 1 2 3]


In [ ]:
x=random.choice([1,2,3])
print(x)

3


In [ ]:
x=random.choice([3,9],p=[0.5,0.5],size=(3,4))
print(x)

[[3 3 3 9]
 [9 9 3 9]
 [9 3 3 9]]


In [ ]:
x=random.choice([3,9],p=[0.5,0.5],size=(3,4))
print(x)